### ISSUE TITLE
Keybindings and key-events

### ISSUE THREAD

**Issue by rubyFeedback** [libui-ng/libui-ng#301] opened 2024-11-23 04:45 UTC
So, this may not be implemented any time soon, but I wanted to make my case nonetheless.

In ruby-gtk3 I make heavy use of keybindings, aka accelerators. For instance, when I can input numbers into a widget, such as 0, 1, 2, 3, and so forth, I tend to associate this usually via Alt+0, Alt+1, Alt+2 and so forth. (Alt is a key on my keyboard; not sure if there is another english name for it, but it is usually situated to the left of the large space key, on the bottom of the keyboard.)

I even use this via shortcuts in actual ruby code such as:

    .keycombo('Alt+1') { run_this_method(1) }
    .keycombo('Alt+2') { run_this_method(2) }

And so forth. (This is not necessarily 1:1 the code I use in ruby; I Just wanted to show how I tend to use it, e. g. a dedicated method, then I pass a String into it that has the shortcut key combination, and then I will call a dedicated second method that actually handles these key-press outcomes.)

Another key-combination I tend to use is "q" or "Alt+q" to quickly quit an application. I use that a LOT in ruby-gtk3.

In libui I think this is currently not possible. I'd like to have that on the windows platform in particular, since it is so useful. For instance, if you have multiple entries in an application, being able to quickly jump to them is also useful, e. g. Alt+1 to the first entry, Alt+2 to the second entry, and so forth.

I know a little bit how this happens via GTK (on linux), but I have no idea how this may work on windows. It may be easier to first add this onto gtk (thus linux) since this is quite well-documented, such as here: https://docs.gtk.org/gtk3/key-bindings.html.

Does anyone know how the windows platform handles keybinding events, via C/C++? How difficult would it be to add basic key-combination support via libui?

At any rate, I wanted to suggest this, as I think it is super-useful for GUIs if we can handle key-combinations.

**Comment by cody271** [comment] 2024-12-08 08:29
Duplicate of #219

**Closed by cody271** 2024-12-08 08:29 UTC
