### ISSUE TITLE
fix windows bad performace?

### ISSUE THREAD

**Issue by e1732a364fed** [libui-ng/libui-ng#161] opened 2022-12-16 09:22 UTC
related issues:

https://github.com/andlabs/libui/issues/311

https://github.com/andlabs/ui/issues/184

Since the old project is dead, I think we should pay attention to this too.

**Comment by e1732a364fed** [comment] 2022-12-16 10:00
here's my script for temporarily fix this 

```
import sys

def comment_out_lines(filename, string_to_search, end_string, comment_char):
  # Open the file in read mode
  with open(filename, 'r') as file:
    # Read all lines in the file
    lines = file.readlines()

  # Initialize the commenting flag
  commenting = False

  # Open the file in write mode
  with open(filename, 'w') as file:
    # Iterate over all lines
    for line in lines:
      # Check if the string is present in the line
      if string_to_search in line:
        # Set the flag to indicate that we are in the commented out section
        commenting = True
      
      # If we are in the commented out section, add the comment character at the beginning of the line
      if commenting:
        file.write(comment_char + line)
      # Otherwise, write the original line
      else:
        file.write(line)

      if end_string in line:
        # If the end string is found, reset the flag
        commenting = False


# Test the function
comment_out_lines('windows/parent.cpp', 'case WM_CTLCOLORSTATIC:',"return TRUE", '//')

comment_out_lines('windows/container.cpp', 'case WM_PAINT:',"return 0", '//')
comment_out_lines('windows/container.cpp', 'case WM_PRINTCLIENT:',"return 0", '//')


```

**Comment by szanni** [comment] 2022-12-17 03:00
I've recently been looking into this myself too. I'll check what your patches do. Apparently some people found some work arounds that I have been unable to reproduce so far.

Your code will probably trigger weird artifacts in some cases, at least that's what is suggested in the original issues you quoted. I have personally been unable to reproduce the supposed paint artifacts as well. Those might be related to certain theming?

**Comment by e1732a364fed** [comment] 2022-12-17 03:24
Just run the controls gallery example on windows, and when you resize the window, you'll see it's very laggy.

My patch is just a POC of a solution mentioned in the issue, to comment out some lines.

**Comment by nptr** [comment] 2023-03-24 18:55
I also encountered this issue during my work on a [libui-rs](https://github.com/libui-rs/libui) successor.
The changes proposed by the above script work well enough on my Win7 and Win10. The caveat is, that the tab page background is now "dialog gray" rather than "white", but it's worth it. No other artifacts related to this from what i can see. 
I assume issues arise when the tab page background isn't solid color or maybe even deviates from the default dialog color?

For completeness, here is my (git applicable) patch: [fix_container_performance.txt](https://github.com/libui-ng/libui-ng/files/11065557/fix_container_performance.txt) based on commit 8015b825ac1b054c10bb4054810d12aa2519911c and a screenshot:

![controlgallery_win_lists](https://user-images.githubusercontent.com/5485569/227614845-1ec23077-df4c-4453-87fd-a67aec9e8e6d.png)

**Comment by cody271** [comment] 2023-03-25 05:05
> here is my (git applicable) patch: [fix_container_performance.txt](https://github.com/libui-ng/libui-ng/files/11065557/fix_container_performance.txt) based on commit [8015b82](https://github.com/libui-ng/libui-ng/commit/8015b825ac1b054c10bb4054810d12aa2519911c)
> 
I've just tested this locally on Win11. Wow, dramatic increase in the FPS of the app! 👍

Can you submit a PR for this patch to be better reviewed and merged? Thanks

**Closed** 2023-04-10 07:26 UTC
